- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/js/model/options.js
- popup/js/search/flexSearch.js
This allows to have include search mode with precide, too
> Introducing search.matchAlgorithm option with new "includes" mode 

- popup/js/model/options.js
- popup/js/search/common.js
- popup/js/search/defaultEntries.js
- popup/js/search/flexSearch.js
- popup/js/view/searchView.js
> Improve default search result behavior

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- bin/createDist.sh
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/js/helper/browserApi.js
- popup/js/model/searchData.js
- popup/js/search/defaultEntries.js
minor refactoring to express cross browser compat
> Make extension work with Opera

- package-lock.json
- package.json
- popup/js/helper/browserApi.js
- popup/js/model/options.js
- popup/js/view/searchView.js
- sass/style.scss
> Allow tab navigation across windows

- .github/workflows/ci.yml
- package-lock.json
- package.json
- popup/js/helper/browserApi.js
- popup/js/model/options.js
- popup/js/search/common.js
- popup/js/search/defaultEntries.js
> New option to display last visited tabs on default entries

- CHANGELOG.md
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/index.html
- popup/js/model/options.js
- popup/options.html
- popup/tipps.html
- sass/style.scss
> Add inline tipps to popup

- .eslintrc.json
- .vscode/settings.json
- CHANGELOG.md
- README.md
- bin/updateLibs.sh
- cypress/integration/options.js
- package-lock.json
- package.json
- popup/index.html
- popup/js/helper/browserApi.js
- popup/js/model/options.js
- popup/js/model/searchData.js
- popup/js/search/common.js
- popup/js/search/defaultEntries.js
- popup/js/search/flexSearch.js
- popup/js/search/fuseSearch.js
- popup/js/search/searchEngines.js
- popup/js/view/editOptionsView.js
- popup/js/view/searchView.js
- popup/options.html
- popup/tipps.html
- popup/tips.html
- sass/style.scss
> Easier user options

- README.md
- package-lock.json
- package.json
> Fixing link to options.js in README

- README.md
There is a broken link in the readme.
> doc: update link to options in readme

- CHANGELOG.md
- cypress/support/commands.js
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/index.html
- popup/js/helper/utils.js
- popup/js/initOptions.js
- popup/js/initSearch.js
- popup/js/model/options.js
- popup/js/search/common.js
- popup/js/search/simpleSearch.js
- popup/options.html
- popup/tips.html
- sass/style.scss
> Improve Error Handling

- CHANGELOG.md
- bin/updateLibs.sh
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/index.html
> Don't bundle external libraries into vendor.min.js anymore

- README.md
- package-lock.json
- package.json
- popup/js/model/options.js
- popup/js/search/common.js
- popup/js/search/searchEngines.js
- sass/style.scss
Suggestions from #45 
Closes #45
> Improvements to custom search engines feature

- CHANGELOG.md
- bin/createDist.sh
- cypress/e2e/search.cy.js
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/js/search/common.js
- popup/js/search/defaultEntries.js
- popup/js/view/searchView.js
This fixes the missing close icon in distribution(s) and hopefully also fixes the previously buggy behavior when closing tabs. This used to caused glitches in closing wrong tabs and re-drawing the new reduced result set.
> Fix missing close icon and update dependencies

- CHANGELOG.md
- bin/createDist.sh
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- **FIXED**: Used wrong icon (edit) for closing tabs
> Fix wrong icon for closing tabs

- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/js/helper/browserApi.js
- popup/js/initSearch.js
- popup/js/model/options.js
- popup/js/model/searchData.js
- popup/js/search/common.js
- popup/js/view/editBookmarkView.js
- popup/js/view/searchView.js
> Adding new debug option, disable logging and performance measuring by default

- CHANGELOG.md
- popup/js/search/fuzzySearch.js
to support chinese and other characters
Relates #87 - solution suggested by @c0001
> Adding interSplit option to fuzzy search 

- README.md
- popup/js/model/options.js
- popup/js/search/fuzzySearch.js
Add guide how to fix uFuzzy for CJK chars
Thanks to c0001 for providing original idea in PR #90
Relates to #87 #90
> Allow passing custom uFuzzy options. 

- popup/js/view/searchView.js
> Apply bookmarkColor option also to corresponding badge in search results

- package-lock.json
- package.json
- popup/js/helper/browserApi.js
- popup/js/model/options.js
- popup/js/view/searchView.js
- popup/tips.html
- sass/style.scss
Resolves #98 
But this PR takes a more conservative approach by only shortening title if it seems to be an URL. 
Doing this in general is more tricky than it seems and might have undesired side effects in some situations.
> Better handle long title values in case they're just URLs anyway

- CHANGELOG.md
- README.md
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/js/view/searchView.js
Fixes #112
Fixes https://github.com/Fannon/search-bookmarks-history-and-tabs/discussions/111
> Fix open URL not working when there are multiple windows

- CHANGELOG.md
- bin/createDist.sh
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- sass/style.scss
- **FIXED**: Fixed missing CSS font style for tagging view
> Fix missing CSS style for tagging view

- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/js/model/searchData.js
> Fix potential crash if history item has no ID

- CHANGELOG.md
- Tips.md
- popup/css/style.css
> Style and tips improvements

- CHANGELOG.md
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/index.html
- popup/js/view/editBookmarkView.js
This can potentially mess up the text display in the search input form field.
Also fixes #146 146
> Fix: Disable autocomplete in search input field

- .vscode/settings.json
- CHANGELOG.md
- popup/index.html
- popup/js/initSearch.js
- popup/js/search/defaultEntries.js
- popup/js/search/fuzzySearch.js
- **IMPROVED**: Performance of initial load
- Lazy load uFuzzy library only when fuzzy search is used
- **CHANGED**: Initial load now only looks for bookmarks matching the current URL, not starting with it
> Lazy load uFuzzy only for fuzzy search

- CHANGELOG.md
- README.md
- manifest.firefox.json
- manifest.json
- package-lock.json
- package.json
- popup/js/helper/browserApi.js
Resolves #151 
Tag filtering works the following way: 
* Tag is only detected if it starts with ` #` (needs precluding space)
* Tags that start with a number are ignored.
> Filter tags to avoid issue / ticket numbers to become tags

- CHANGELOG.md
- popup/css/style.css
> Fix highlighting for Light Theme Mode

- .github/workflows/ci.yml
- AGENTS.md
- README.md
- jest.config.js
- package-lock.json
- package.json
- popup/js/helper/__tests__/utils.test.js
- **Unit Testing Setup**: Added Jest framework and initial unit tests for utility functions
- **Documentation**: Introduced AGENTS.md file for development guidelines
- **CI Improvement**: Modified GitHub Actions workflow to run unit tests as a separate job, ensuring tests execute efficiently after build completion
> Add Jest unit testing setup and initial tests
